#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate complete HZK24 font data for all GB2312 characters

This script generates C code with all GB2312 characters (6,763 characters)
from the HZK24S font file.

HZK24S format:
- 24x24 dot matrix
- 72 bytes per character (24*24/8 = 72)
- GB2312 encoding

Usage:
    python generate_full_hzk24.py HZK24S hzk24_full.c

This will create a ~500KB C file with all Chinese characters.
"""

import sys
import os

def generate_full_gb2312(hzk24_file, output_file):
    """
    Generate C code with all GB2312 characters
    
    GB2312 encoding:
    - Area (区): 0xA1-0xF7 (87 areas)
    - Position (位): 0xA1-0xFE (94 positions)
    - Total: 87 * 94 = 8,178 positions
    - Actual characters: ~6,763 (some positions are empty)
    
    HZK24S format:
    - 24x24 pixels = 72 bytes per character
    """
    
    if not os.path.exists(hzk24_file):
        print(f"Error: HZK24S file not found: {hzk24_file}")
        print("Please download HZK24S from:")
        print("  https://github.com/aguegu/BitmapFont/raw/master/font/HZK24S")
        sys.exit(1)
    
    print(f"Reading HZK24S font file: {hzk24_file}")
    
    # Read entire HZK24S file
    with open(hzk24_file, 'rb') as f:
        hzk_data = f.read()
    
    expected_size = 94 * 94 * 72  # 635,232 bytes
    if len(hzk_data) < expected_size:
        print(f"Warning: HZK24S file size is {len(hzk_data)} bytes, expected {expected_size}")
    
    print(f"Generating C code to {output_file}...")
    
    char_count = 0
    
    with open(output_file, 'w', encoding='utf-8') as f:
        # Write header
        f.write("""/**
 * @file hzk24_full.c
 * @brief Complete HZK24 font data for all GB2312 characters
 * 
 * This file contains all 6,763 GB2312 Chinese characters.
 * Font size: 24x24 pixels
 * File size: ~500KB
 * 
 * Generated by generate_full_hzk24.py
 * DO NOT EDIT MANUALLY
 * 
 * @copyright Copyright (c) 2021-2025 Tuya Inc. All Rights Reserved.
 */

#include "hzk24.h"
#include <string.h>

typedef struct {
    uint8_t gb_high;
    uint8_t gb_low;
    uint8_t data[72];
} hzk24_char_t;

static const hzk24_char_t hzk24_embedded[] = {
""")
        
        # Generate all GB2312 characters
        # GB2312 uses area code (qu) and position code (wei)
        for qu in range(94):  # 0-93
            for wei in range(94):  # 0-93
                gb_high = 0xA1 + qu
                gb_low = 0xA1 + wei
                
                # Calculate offset in HZK24S file
                offset = (qu * 94 + wei) * 72
                
                if offset + 72 > len(hzk_data):
                    continue
                
                # Read font data
                font_data = hzk_data[offset:offset+72]
                
                # Check if this is a valid character (not all zeros)
                if all(b == 0 for b in font_data):
                    continue
                
                # Try to decode the character for comment
                try:
                    char_bytes = bytes([gb_high, gb_low])
                    char_str = char_bytes.decode('gbk')
                    comment = f" // {char_str} ({gb_high:02X}{gb_low:02X})"
                except:
                    comment = f" // ({gb_high:02X}{gb_low:02X})"
                
                # Write character entry
                f.write(f"    {{0x{gb_high:02X}, 0x{gb_low:02X}, {{{comment}\n")
                
                # Write font data in rows of 12 bytes
                for i in range(0, 72, 12):
                    f.write("        ")
                    for j in range(min(12, 72 - i)):
                        f.write(f"0x{font_data[i+j]:02X},")
                    f.write("\n")
                
                f.write("    }},\n")
                
                char_count += 1
                
                # Progress indicator
                if char_count % 100 == 0:
                    print(f"  Generated {char_count} characters...")
        
        # Write footer
        f.write("""};

#define HZK24_EMBEDDED_COUNT (sizeof(hzk24_embedded) / sizeof(hzk24_char_t))

int hzk24_get_font_data(uint8_t gb_high, uint8_t gb_low, uint8_t *buffer)
{
    if (!buffer) {
        return -1;
    }
    
    // Binary search for better performance
    int left = 0;
    int right = HZK24_EMBEDDED_COUNT - 1;
    
    while (left <= right) {
        int mid = (left + right) / 2;
        uint16_t target = ((uint16_t)gb_high << 8) | gb_low;
        uint16_t current = ((uint16_t)hzk24_embedded[mid].gb_high << 8) | 
                          hzk24_embedded[mid].gb_low;
        
        if (current == target) {
            memcpy(buffer, hzk24_embedded[mid].data, 72);
            return 0;
        } else if (current < target) {
            left = mid + 1;
        } else {
            right = mid - 1;
        }
    }
    
    // Character not found
    memset(buffer, 0, 72);
    return -1;
}

int hzk24_has_font(uint8_t gb_high, uint8_t gb_low)
{
    // Binary search
    int left = 0;
    int right = HZK24_EMBEDDED_COUNT - 1;
    
    while (left <= right) {
        int mid = (left + right) / 2;
        uint16_t target = ((uint16_t)gb_high << 8) | gb_low;
        uint16_t current = ((uint16_t)hzk24_embedded[mid].gb_high << 8) | 
                          hzk24_embedded[mid].gb_low;
        
        if (current == target) {
            return 1;
        } else if (current < target) {
            left = mid + 1;
        } else {
            right = mid - 1;
        }
    }
    
    return 0;
}
""")
    
    print(f"\nDone!")
    print(f"Generated {char_count} characters")
    print(f"File size: {os.path.getsize(output_file)} bytes (~{os.path.getsize(output_file)//1024}KB)")
    print(f"\nTo use this font:")
    print(f"  1. Create header file: lib/Fonts/hzk24.h")
    print(f"  2. Copy generated file: cp {output_file} lib/Fonts/hzk24.c")
    print(f"  3. Update CMakeLists.txt to include hzk24.c")
    print(f"  4. Rebuild: tos.py build")

def main():
    if len(sys.argv) < 3:
        print("Usage: python generate_full_hzk24.py <HZK24S_file> <output.c>")
        print("")
        print("Example:")
        print("  python generate_full_hzk24.py HZK24S hzk24_full.c")
        print("")
        print("This will generate a C file with all GB2312 characters (~500KB)")
        print("")
        print("Download HZK24S from:")
        print("  https://github.com/aguegu/BitmapFont/raw/master/font/HZK24S")
        sys.exit(1)
    
    hzk24_file = sys.argv[1]
    output_file = sys.argv[2]
    
    generate_full_gb2312(hzk24_file, output_file)

if __name__ == '__main__':
    main()
