#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate HZK16 font data from text file

This script extracts unique Chinese characters from a text file
and generates C code with their HZK16 font data.

Usage:
    python generate_hzk16_data.py input.txt hzk16 output.c

Requirements:
    - HZK16 font file (download from internet, about 260KB)
    - Input text file in GBK encoding
"""

import sys
import os

def read_hzk16_font(hzk16_file, gb_high, gb_low):
    """
    Read font data for a GBK character from HZK16 file
    
    Args:
        hzk16_file: Path to HZK16 font file
        gb_high: GBK high byte (0x81-0xFE)
        gb_low: GBK low byte (0x40-0xFE, except 0x7F)
    
    Returns:
        32 bytes of font data, or None if not found
    """
    if not os.path.exists(hzk16_file):
        return None
    
    # Calculate offset in HZK16 file
    # HZK16 uses area code (qu) and position code (wei)
    qu = gb_high - 0xA1
    wei = gb_low - 0xA1
    
    if qu < 0 or qu >= 94 or wei < 0 or wei >= 94:
        return None
    
    offset = (qu * 94 + wei) * 32
    
    try:
        with open(hzk16_file, 'rb') as f:
            f.seek(offset)
            data = f.read(32)
            if len(data) == 32:
                return data
    except:
        pass
    
    return None

def extract_chinese_chars(text_file):
    """
    Extract unique Chinese characters from text file
    
    Args:
        text_file: Path to GBK encoded text file
    
    Returns:
        Set of (gb_high, gb_low) tuples
    """
    chars = set()
    
    try:
        with open(text_file, 'rb') as f:
            content = f.read()
        
        i = 0
        while i < len(content):
            byte = content[i]
            
            # Check if it's GBK lead byte
            if byte >= 0x81 and byte <= 0xFE and i + 1 < len(content):
                byte2 = content[i + 1]
                if byte2 >= 0x40 and byte2 <= 0xFE and byte2 != 0x7F:
                    chars.add((byte, byte2))
                    i += 2
                    continue
            
            i += 1
        
        return chars
    
    except Exception as e:
        print(f"Error reading file: {e}")
        return set()

def generate_c_code(chars_data, output_file):
    """
    Generate C code with font data
    
    Args:
        chars_data: List of (gb_high, gb_low, font_data) tuples
        output_file: Output C file path
    """
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("""/**
 * @file hzk16_generated.c
 * @brief Auto-generated HZK16 font data
 * 
 * Generated by generate_hzk16_data.py
 * DO NOT EDIT MANUALLY
 */

#include "hzk16.h"
#include <string.h>

typedef struct {
    uint8_t gb_high;
    uint8_t gb_low;
    uint8_t data[32];
} hzk16_char_t;

static const hzk16_char_t hzk16_embedded[] = {
""")
        
        for gb_high, gb_low, font_data in chars_data:
            # Try to decode character for comment
            try:
                char_bytes = bytes([gb_high, gb_low])
                char_str = char_bytes.decode('gbk')
                comment = f" // {char_str} ({gb_high:02X}{gb_low:02X})"
            except:
                comment = f" // ({gb_high:02X}{gb_low:02X})"
            
            f.write(f"    {{0x{gb_high:02X}, 0x{gb_low:02X}, {{{comment}\n")
            
            # Write font data in rows of 12 bytes
            for i in range(0, 32, 12):
                f.write("        ")
                for j in range(min(12, 32 - i)):
                    f.write(f"0x{font_data[i+j]:02X},")
                f.write("\n")
            
            f.write("    }},\n")
        
        f.write("""};

#define HZK16_EMBEDDED_COUNT (sizeof(hzk16_embedded) / sizeof(hzk16_char_t))

int hzk16_get_font_data(uint8_t gb_high, uint8_t gb_low, uint8_t *buffer)
{
    if (!buffer) {
        return -1;
    }
    
    for (int i = 0; i < HZK16_EMBEDDED_COUNT; i++) {
        if (hzk16_embedded[i].gb_high == gb_high && 
            hzk16_embedded[i].gb_low == gb_low) {
            memcpy(buffer, hzk16_embedded[i].data, 32);
            return 0;
        }
    }
    
    memset(buffer, 0, 32);
    return -1;
}

int hzk16_has_font(uint8_t gb_high, uint8_t gb_low)
{
    for (int i = 0; i < HZK16_EMBEDDED_COUNT; i++) {
        if (hzk16_embedded[i].gb_high == gb_high && 
            hzk16_embedded[i].gb_low == gb_low) {
            return 1;
        }
    }
    return 0;
}
""")

def main():
    if len(sys.argv) < 4:
        print("Usage: python generate_hzk16_data.py <input.txt> <hzk16_file> <output.c>")
        print("")
        print("Example:")
        print("  python generate_hzk16_data.py novel.txt HZK16 hzk16_generated.c")
        print("")
        print("Download HZK16 from: https://github.com/aguegu/BitmapFont/blob/master/font/HZK16")
        sys.exit(1)
    
    text_file = sys.argv[1]
    hzk16_file = sys.argv[2]
    output_file = sys.argv[3]
    
    print(f"Extracting Chinese characters from {text_file}...")
    chars = extract_chinese_chars(text_file)
    print(f"Found {len(chars)} unique Chinese characters")
    
    if not os.path.exists(hzk16_file):
        print(f"Warning: HZK16 file not found: {hzk16_file}")
        print("Generating empty font data...")
        chars_data = [(gb_high, gb_low, bytes(32)) for gb_high, gb_low in sorted(chars)]
    else:
        print(f"Reading font data from {hzk16_file}...")
        chars_data = []
        for gb_high, gb_low in sorted(chars):
            font_data = read_hzk16_font(hzk16_file, gb_high, gb_low)
            if font_data:
                chars_data.append((gb_high, gb_low, font_data))
            else:
                print(f"Warning: No font data for {gb_high:02X}{gb_low:02X}")
        
        print(f"Successfully read {len(chars_data)} characters")
    
    print(f"Generating C code to {output_file}...")
    generate_c_code(chars_data, output_file)
    
    print("Done!")
    print(f"Generated {len(chars_data)} characters")
    print(f"Estimated size: {len(chars_data) * 34} bytes")

if __name__ == '__main__':
    main()
